import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authLoginUrl, authLogoutUrl, AuthState, getAuthState } from '../api';
import { AppHeader } from '../components/app-header';
import { SeoHead } from '../components/seo-head';
import { syncLabelKey, useI18n } from '../i18n';
import { backgroundWorkspaceSync, WorkspaceSyncSnapshot } from '../workspace-sync';
// Default Mongolian labels: Нэвтрэх, Гарах.
export default function AccountScreen(){const{t}=useI18n();const[auth,setAuth]=useState<AuthState>();const[error,setError]=useState(false);const[sync,setSync]=useState<WorkspaceSyncSnapshot>(backgroundWorkspaceSync.getSnapshot());const load=async()=>{setError(false);try{setAuth(await getAuthState())}catch{setError(true)}};useEffect(()=>{void load();const unsubscribe=backgroundWorkspaceSync.subscribe(()=>setSync(backgroundWorkspaceSync.getSnapshot()));return()=>{unsubscribe();}},[]);return <SafeAreaView style={s.page}><SeoHead title="ENKH Account" description="ENKH account болон хувийн cloud workspace-ийн удирдлага." path="/account" noIndex/><AppHeader active="account"/><ScrollView contentContainerStyle={s.content}><Text accessibilityRole="header" style={s.title}>{t('account.title')}</Text><Text style={s.subtitle}>{t('account.subtitle')}</Text>{!auth&&!error&&<View style={s.card}><ActivityIndicator/><Text style={s.body}>{t('account.checking')}</Text></View>}{error&&<View style={s.card}><Text style={s.cardTitle}>{t('account.unavailable')}</Text><Button label={t('common.retry')} onPress={()=>void load()}/></View>}{auth&&!auth.authenticated&&<View style={s.card}><Text style={s.cardTitle}>{t('account.signInTitle')}</Text><Text style={s.body}>{t('account.signInHelp')}</Text><Button label={t('account.signIn')} onPress={()=>void Linking.openURL(authLoginUrl)}/></View>}{auth?.authenticated&&<View style={s.card}><Text style={s.label}>{t('account.yours')}</Text><Text style={s.cardTitle}>{auth.user?.name||auth.user?.email||t('account.user')}</Text><View style={s.statusRow}><View style={s.statusDot}/><Text style={s.statusText}>{t(syncLabelKey(sync.phase))}</Text></View><Text style={s.body}>{t('account.cloudActive')}</Text><Pressable accessibilityRole="link" onPress={()=>void Linking.openURL(authLogoutUrl)} style={s.secondary}><Text style={s.secondaryText}>{t('account.signOut')}</Text></Pressable></View>}</ScrollView></SafeAreaView>}
function Button({label,onPress}:{label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.button}><Text style={s.buttonText}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F8FD'},content:{width:'100%',maxWidth:920,alignSelf:'center',paddingHorizontal:20,paddingVertical:36,gap:16},title:{fontSize:36,fontWeight:'900',color:'#102A43'},subtitle:{fontSize:15,lineHeight:23,color:'#627D98'},card:{padding:24,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFEAF7'},label:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#829AB1'},cardTitle:{marginTop:10,fontSize:21,fontWeight:'800',color:'#102A43'},statusRow:{marginTop:14,flexDirection:'row',alignItems:'center',gap:8},statusDot:{width:8,height:8,borderRadius:4,backgroundColor:'#2F855A'},statusText:{fontSize:14,fontWeight:'800',color:'#276749'},body:{marginTop:9,fontSize:15,lineHeight:23,color:'#526D82'},button:{alignSelf:'flex-start',minHeight:48,justifyContent:'center',marginTop:18,paddingHorizontal:18,borderRadius:13,backgroundColor:'#0B57D0'},buttonText:{color:'#FFF',fontWeight:'800'},secondary:{alignSelf:'flex-start',minHeight:44,justifyContent:'center',marginTop:18,paddingHorizontal:14,borderRadius:12,backgroundColor:'#EAF2FF'},secondaryText:{fontWeight:'800',color:'#0B57D0'}});
