import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '../components/app-header';
import { SeoHead } from '../components/seo-head';
import { AdminApiError, cancelReminder, createReminder, listReminders, Reminder, updateReminder } from '../api';
import { DEFAULT_TIMEZONE, localDateTimeToUtc, parseSafeNaturalReminder } from '../reminder-time';
import { addEntry, createSession, loadWorkspace, saveWorkspace } from '../workspace-store';
import { backgroundWorkspaceSync } from '../workspace-sync';

const labels = { scheduled: 'Товлогдсон', processing: 'Хүргэж байна', delivered: 'Хүргэгдсэн', failed: 'Хүргэлт амжилтгүй', cancelled: 'Цуцлагдсан' } as const;
function tomorrow() { const date = new Date(); date.setDate(date.getDate() + 1); return date.toISOString().slice(0, 10); }

export default function ReminderActionScreen() {
  const [natural,setNatural]=useState(''); const [title,setTitle]=useState(''); const [note,setNote]=useState('');
  const [date,setDate]=useState(''); const [time,setTime]=useState('10:00'); const [timezone,setTimezone]=useState(DEFAULT_TIMEZONE);
  const [items,setItems]=useState<Reminder[]>([]); const [editing,setEditing]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  const refresh=async()=>{try{setItems(await listReminders());}catch(e){setNotice(e instanceof AdminApiError&&e.status===401?'Сануулагч ашиглахын тулд Account-аар нэвтэрнэ үү.':'Сануулагчийн жагсаалт түр холбогдсонгүй.');}};
  useEffect(()=>{setDate(tomorrow());void refresh();},[]);
  const parse=()=>{const value=parseSafeNaturalReminder(natural);if(!value){setNotice('Огноо эсвэл цаг тодорхойгүй байна. Доорх талбаруудаас заавал нягтална уу.');return;}setTitle(value.title);setDate(value.date);setTime(value.time);setNotice('Утгыг задлав. Хадгалахаас өмнө огноо, цагийг нягтална уу.');};
  const reset=()=>{setEditing(null);setTitle('');setNote('');setDate(tomorrow());setTime('10:00');};
  const submit=async()=>{const scheduledAt=localDateTimeToUtc(date,time,timezone);if(!title.trim()||!scheduledAt||new Date(scheduledAt).getTime()<=Date.now()+30000){setNotice('Ирээдүйн тодорхой огноо, цаг болон гарчгийг нягтална уу.');return;}setBusy(true);setNotice('');try{
    const input={title:title.trim(),note:note.trim(),scheduledAt,timezone,deliveryChannel:'in_app' as const}; const saved=editing?await updateReminder(editing,input):await createReminder(input);
    if(!editing){let workspace=loadWorkspace().state;const created=createSession(workspace,'action',saved.title);workspace=addEntry(created.state,{sessionId:created.session.id,role:'assistant',type:'action',actionId:'reminder',content:`${saved.title} · ${new Date(saved.scheduledAt).toLocaleString()}`});if(saveWorkspace(workspace))backgroundWorkspaceSync.schedule(workspace);}
    setNotice(editing?'Сануулагч шинэ хуваариар хадгалагдлаа.':'Сануулагч товлогдлоо. Browser хаалттай байсан ч ENKH хадгална.');reset();await refresh();
  }catch(e){setNotice(e instanceof AdminApiError&&e.status===401?'Нэвтрэх шаардлагатай.':'Хадгалж чадсангүй. Мэдээллээ алдалгүй дахин оролдоно уу.');}finally{setBusy(false);}};
  const edit=(r:Reminder)=>{const local=new Date(r.scheduledAt);setEditing(r.id);setTitle(r.title);setNote(r.note);setDate(local.toLocaleDateString('en-CA',{timeZone:r.timezone}));setTime(local.toLocaleTimeString('en-GB',{timeZone:r.timezone,hour:'2-digit',minute:'2-digit'}));setTimezone(r.timezone);setNotice('Хуучин хуваарь зөвхөн шинэ утгыг хадгалсны дараа солигдоно.');};
  const cancel=async(id:string)=>{setBusy(true);try{await cancelReminder(id);setNotice('Сануулагч цуцлагдлаа. Хүргэгдэхгүй.');await refresh();}catch{setNotice('Цуцалж чадсангүй. Дахин оролдоно уу.');}finally{setBusy(false);}};
  return <SafeAreaView style={s.page}><SeoHead title="ENKH Сануулагч" description="Тогтвортой хадгалагдах ENKH сануулагч." path="/action-reminder" noIndex/><AppHeader active="tools"/><ScrollView contentContainerStyle={s.content}>
    <Text accessibilityRole="header" style={s.h1}>Сануулагч</Text><Text style={s.sub}>Огноо, цагийг нягтлаад хадгална. v1 хүргэлт ENKH дотор харагдана.</Text>
    <View style={s.card}><Text style={s.label}>Байгалийн хэлээр бичих</Text><TextInput value={natural} onChangeText={setNatural} placeholder="Маргааш 10:00-д Мягмартай уулзахыг сануул." style={s.input}/><Pressable onPress={parse} style={s.secondary}><Text style={s.secondaryText}>Утгыг задлах</Text></Pressable>
      <Text style={s.label}>Гарчиг / сануулах зүйл</Text><TextInput value={title} onChangeText={setTitle} maxLength={160} style={s.input}/><Text style={s.label}>Нэмэлт тэмдэглэл</Text><TextInput value={note} onChangeText={setNote} maxLength={2000} multiline style={[s.input,s.note]}/>
      <View style={s.row}><View style={s.field}><Text style={s.label}>Огноо (YYYY-MM-DD)</Text><TextInput value={date} onChangeText={setDate} style={s.input}/></View><View style={s.field}><Text style={s.label}>Цаг (HH:mm)</Text><TextInput value={time} onChangeText={setTime} style={s.input}/></View></View>
      <Text style={s.label}>Timezone</Text><TextInput value={timezone} onChangeText={setTimezone} style={s.input}/><Text style={s.hint}>Хүргэлт: ENKH дотор · UTC-аар найдвартай товлоно</Text>
      <Pressable disabled={busy} onPress={()=>void submit()} style={s.primary}><Text style={s.primaryText}>{busy?'Хадгалж байна…':editing?'Шинэ хуваарийг хадгалах':'Сануулагч товлох'}</Text></Pressable>{editing&&<Pressable onPress={reset} style={s.secondary}><Text style={s.secondaryText}>Засварыг болих</Text></Pressable>}
    </View>{notice?<Text accessibilityLiveRegion="polite" style={s.notice}>{notice}</Text>:null}
    <Text accessibilityRole="header" style={s.h2}>Сануулагчид</Text>{items.length===0?<View style={s.empty}><Text>Одоогоор сануулагч алга.</Text></View>:items.map(r=><View key={r.id} style={s.item}><View style={s.itemMain}><Text style={s.itemTitle}>{r.title}</Text><Text style={s.meta}>{new Date(r.scheduledAt).toLocaleString('mn-MN',{timeZone:r.timezone})} · {r.timezone}</Text><Text style={s.status}>{labels[r.status]}</Text></View>{(r.status==='scheduled'||r.status==='failed')&&<View style={s.actions}><Pressable onPress={()=>edit(r)} style={s.small}><Text>Засах</Text></Pressable><Pressable onPress={()=>void cancel(r.id)} style={s.small}><Text>Цуцлах</Text></Pressable></View>}</View>)}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F8FD'},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:20,paddingTop:40,paddingBottom:70},h1:{fontSize:38,fontWeight:'900',color:'#102A43'},sub:{marginTop:8,fontSize:16,lineHeight:24,color:'#627D98'},card:{marginTop:24,padding:22,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFEAF7'},label:{marginTop:14,marginBottom:6,fontWeight:'800',color:'#243B53'},input:{minHeight:48,paddingHorizontal:14,paddingVertical:12,borderWidth:1,borderColor:'#BCCCDC',borderRadius:12,backgroundColor:'#FFF',fontSize:16},note:{minHeight:90,textAlignVertical:'top'},row:{flexDirection:'row',flexWrap:'wrap',gap:12},field:{flexGrow:1,flexBasis:220},hint:{marginTop:12,color:'#627D98'},primary:{minHeight:48,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#0B57D0'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{minHeight:44,marginTop:10,alignItems:'center',justifyContent:'center',borderRadius:12,borderWidth:1,borderColor:'#9FB3C8'},secondaryText:{fontWeight:'800',color:'#0B57D0'},notice:{marginTop:14,padding:14,borderRadius:12,backgroundColor:'#EAF2FF',color:'#243B53'},h2:{marginTop:34,fontSize:24,fontWeight:'900',color:'#102A43'},empty:{marginTop:12,padding:20,borderRadius:16,backgroundColor:'#FFF'},item:{marginTop:12,padding:18,borderRadius:16,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFEAF7',flexDirection:'row',flexWrap:'wrap',gap:12},itemMain:{flex:1,minWidth:220},itemTitle:{fontSize:17,fontWeight:'900',color:'#102A43'},meta:{marginTop:6,color:'#627D98'},status:{marginTop:8,fontWeight:'800',color:'#26713A'},actions:{flexDirection:'row',gap:8},small:{minHeight:44,minWidth:72,alignItems:'center',justifyContent:'center',paddingHorizontal:12,borderRadius:10,backgroundColor:'#EAF2FF'}});
