import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getSystemHealth } from '../api';
import { AppHeader } from '../components/app-header';

type HealthState='loading'|'online'|'offline';
export default function StatusScreen(){const[state,setState]=useState<HealthState>('loading');const check=async()=>{setState('loading');try{setState((await getSystemHealth()).healthy?'online':'offline');}catch{setState('offline');}};useEffect(()=>{void check();},[]);return <SafeAreaView style={styles.page}><AppHeader active="status"/><ScrollView contentContainerStyle={styles.content}>
  <Text accessibilityRole="header" style={styles.title}>System status</Text><Text style={styles.subtitle}>Зардалгүй health check. AI хүсэлт автоматаар илгээхгүй.</Text>
  <View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>ENKH API</Text>{state==='loading'?<ActivityIndicator color="#171717"/>:<Text style={[styles.badge,state==='online'?styles.ok:styles.bad]}>{state==='online'?'ONLINE':'UNAVAILABLE'}</Text>}</View><Text style={styles.body}>Chat, Search, Tools-ийн үндсэн backend холбоо.</Text><Pressable accessibilityRole="button" onPress={()=>void check()} style={styles.button}><Text style={styles.buttonText}>Дахин шалгах</Text></Pressable></View>
  <View style={styles.card}><Text style={styles.cardTitle}>AI ба Search</Text><Text style={styles.body}>Бодит хүсэлт хийх үед баталгаажна. Status дэлгэц paid API call хийхгүй.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Workspace</Text><Text style={styles.body}>Local-first: энэ browser-ийн хадгалалт ашиглана.</Text></View>
</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F8FD'},content:{width:'100%',maxWidth:920,alignSelf:'center',paddingHorizontal:20,paddingVertical:36,gap:14},title:{fontSize:36,fontWeight:'900',color:'#102A43'},subtitle:{fontSize:15,lineHeight:23,color:'#627D98',marginBottom:6},card:{padding:22,borderRadius:20,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFEAF7'},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:12},cardTitle:{fontSize:19,fontWeight:'800',color:'#102A43'},body:{marginTop:8,fontSize:14,lineHeight:22,color:'#526D82'},badge:{overflow:'hidden',paddingHorizontal:10,paddingVertical:6,borderRadius:10,fontSize:11,fontWeight:'900'},ok:{backgroundColor:'#E6F5E9',color:'#236B34'},bad:{backgroundColor:'#FFF0ED',color:'#8B2C20'},button:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',marginTop:14,paddingHorizontal:14,borderRadius:11,backgroundColor:'#0B57D0'},buttonText:{fontSize:13,fontWeight:'800',color:'#FFF'}});
