import { router } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AdminApiError, AdminOverview, adminLoginUrl, getAdminOverview } from '../../api';
import { AppHeader } from '../../components/app-header';
import { SeoHead } from '../../components/seo-head';
import { useI18n } from '../../i18n';

function Metric({label,value}:{label:string;value:string|number}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}

export default function AdminScreen(){
 const{t}=useI18n();const[data,setData]=useState<AdminOverview>();const[status,setStatus]=useState<'loading'|'auth'|'forbidden'|'error'>('loading');
 const load=useCallback(async()=>{setStatus('loading');try{setData(await getAdminOverview())}catch(error){setData(undefined);setStatus(error instanceof AdminApiError&&error.status===401?'auth':error instanceof AdminApiError&&error.status===403?'forbidden':'error')}},[]);
 useEffect(()=>{void load()},[load]);
 return <SafeAreaView style={s.page}><SeoHead title="ENKH Admin" description="ENKH системийн хамгаалагдсан, зөвхөн унших төлөв." path="/admin" noIndex/><AppHeader active="admin"/><ScrollView contentContainerStyle={s.content}><View style={s.heading}><View><Text accessibilityRole="header" style={s.title}>{t('admin.title')}</Text><Text style={s.subtitle}>{t('admin.subtitle')}</Text></View>{data&&<Pressable accessibilityRole="button" onPress={()=>void load()} style={s.secondary}><Text style={s.secondaryText}>{t('common.retry')}</Text></Pressable>}</View>
 {status==='loading'&&!data&&<View style={s.state}><ActivityIndicator/><Text>{t('common.loading')}</Text></View>}
 {status==='auth'&&<State title={t('admin.signIn')} body={t('admin.signInHelp')} actionLabel={t('account.signIn')} action={()=>void Linking.openURL(adminLoginUrl)}/>} {status==='forbidden'&&<State title={t('admin.forbidden')} body={t('admin.forbiddenHelp')}/>} {status==='error'&&<State title={t('admin.unavailable')} body={t('admin.retryHelp')} actionLabel={t('common.retry')} action={()=>void load()}/>} 
 {data&&<><View style={s.notice}><Text style={s.noticeText}>{t('admin.readOnly')}</Text></View><Text style={s.section}>{t('admin.accounts')}</Text><View style={s.grid}><Metric label={t('admin.workspaceAccounts')} value={data.accounts.withWorkspace}/><Metric label={t('admin.workspaceRecords')} value={data.workspaces.records}/><Metric label={t('admin.workspaceUpdated')} value={data.workspaces.updated24h}/></View>
 <Text style={s.section}>{t('admin.reminders')}</Text><View style={s.grid}><Metric label={t('admin.reminderTotal')} value={data.reminders.total}/><Metric label={t('admin.reminderScheduled')} value={data.reminders.scheduled}/><Metric label={t('admin.reminderDelivered')} value={data.reminders.delivered}/><Metric label={t('admin.reminderFailed')} value={data.reminders.failed}/></View>
 <Text style={s.section}>{t('admin.operations')}</Text><View style={s.grid}><Metric label={t('admin.database')} value={data.database.status}/><Metric label={t('admin.messenger24h')} value={data.activity.messengerMessages24h}/><Metric label={t('admin.router')} value={data.services.aiRouter?.configured?t('admin.configured'):t('admin.notConfigured')}/><Metric label={t('admin.page')} value={data.services.pagePublishing?.configured?t('admin.configured'):t('admin.notConfigured')}/></View>
 <View style={s.links}><Pressable accessibilityRole="link" onPress={()=>router.push('/admin/data')} style={s.primary}><Text style={s.primaryText}>{t('admin.data')}</Text></Pressable></View></>}
 </ScrollView></SafeAreaView>
}
function State({title,body,actionLabel,action}:{title:string;body:string;actionLabel?:string;action?:()=>void}){return <View style={s.state}><Text style={s.stateTitle}>{title}</Text><Text style={s.body}>{body}</Text>{action&&<Pressable accessibilityRole="button" onPress={action} style={s.primary}><Text style={s.primaryText}>{actionLabel}</Text></Pressable>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F8FD'},content:{width:'100%',maxWidth:1100,alignSelf:'center',paddingHorizontal:20,paddingVertical:32,paddingBottom:60},heading:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',alignItems:'center',gap:12},title:{fontSize:36,fontWeight:'900',color:'#102A43'},subtitle:{marginTop:7,fontSize:15,lineHeight:23,color:'#627D98'},notice:{marginTop:22,padding:14,borderRadius:14,backgroundColor:'#EAF2FF'},noticeText:{fontWeight:'800',color:'#0B57D0'},section:{marginTop:30,marginBottom:12,fontSize:20,fontWeight:'900',color:'#102A43'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},metric:{flexGrow:1,flexBasis:190,minHeight:120,padding:20,borderRadius:18,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DFEAF7'},metricLabel:{fontSize:13,fontWeight:'800',color:'#627D98'},metricValue:{marginTop:14,fontSize:28,fontWeight:'900',color:'#102A43'},state:{minHeight:260,marginTop:24,alignItems:'center',justifyContent:'center',gap:10,padding:24,borderRadius:18,backgroundColor:'#FFF'},stateTitle:{fontSize:20,fontWeight:'900',color:'#102A43'},body:{textAlign:'center',fontSize:14,lineHeight:22,color:'#627D98'},links:{marginTop:28,flexDirection:'row',flexWrap:'wrap',gap:10},primary:{minHeight:46,justifyContent:'center',paddingHorizontal:18,borderRadius:12,backgroundColor:'#0B57D0'},primaryText:{fontWeight:'800',color:'#FFF'},secondary:{minHeight:44,justifyContent:'center',paddingHorizontal:15,borderRadius:12,backgroundColor:'#EAF2FF'},secondaryText:{fontWeight:'800',color:'#0B57D0'}});
