import { createContext, ReactNode, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type UiLanguage = 'mn' | 'en' | 'zh';
export const LANGUAGE_STORAGE_KEY = 'enkh.ui.language.v1';

const mn = {
  'language.label':'Хэл','language.mn':'Монгол','language.en':'English','language.zh':'中文（简体）',
  'nav.home':'Нүүр','nav.chat':'Chat','nav.search':'Хайлт','nav.workspace':'Workspace','nav.tools':'Tools','nav.account':'Account','nav.status':'System','nav.primary':'Үндсэн цэс','nav.utility':'Account болон system цэс','brand.home':'ENKH нүүр хуудас',
  'common.open':'Нээх →','common.retry':'Дахин оролдох','common.loading':'Ачаалж байна…','common.generate':'Үүсгэх','common.regenerate':'Дахин үүсгэх','common.copy':'Хуулах','common.save':'Хадгалах','common.cancel':'Цуцлах','common.edit':'Засах','common.details':'Дэлгэрэнгүй','common.hideDetails':'Дэлгэрэнгүйг нуух','common.back':'Буцах','common.working':'АЖИЛЛАЖ БАЙНА',
  'home.greeting':'Сайн байна уу!','home.subtitle':'Өнөөдөр юуг амжуулах вэ?','home.prompt':'ENKH-ээс асуух зүйлээ бичнэ үү…','home.ask':'Асуух','home.aboutTitle':'ENKH гэж юу вэ?','home.about':'ENKH буюу Enkh AI нь өдөр тутмын асуулт, эх сурвалжтай вэб хайлт, хувь ба хэмжих нэгжийн тооцоо, текст боловсруулах, мессеж болон бүтэцтэй баримт бичиг бэлтгэхэд тусалдаг Монгол хэл дээрх AI бүтээгдэхүүн юм.','home.what':'Юу хийх вэ?','home.workspace':'Таны ENKH workspace','home.recent':'Сүүлийн ажлууд','home.all':'Бүгдийг харах →','home.empty':'Workspace хоосон байна','home.emptyHelp':'ENKH ашиглахад таны бодит ажлууд энд харагдана.','home.quick':'QUICK TOOLS','home.workspaceOpen':'Workspace нээх →',
  'feature.chat':'Chat','feature.chatDesc':'Ойлгомжтой, үргэлжилсэн яриа','feature.search':'Хайлт','feature.searchDesc':'Эх сурвалжтай бодит хайлт','feature.workspace':'Workspace','feature.workspaceDesc':'Таны хадгалсан ажлууд','feature.tools':'Tools','feature.toolsDesc':'Бодитоор ажиллах хэрэгслүүд',
  'tool.calculation':'Тооцоолол','tool.text':'Текст боловсруулах','tool.message':'Мессеж бэлтгэх','tool.document':'Баримт бичиг','tool.reminder':'Сануулга',
  'tools.title':'ENKH Tools','tools.subtitle':'Таны ажлыг хурдан бэлтгэх бодитоор ажилладаг хэрэгслүүд.','tools.active':'Ажиллаж байгаа','tools.run':'Ажиллуулах','tools.process':'Боловсруулах','tools.draft':'Ноорог бэлтгэх','tools.schedule':'Товлох','tools.calcDesc':'Тоон илэрхийлэл, хувь болон хэмжих нэгжтэй тооцоо.','tools.textDesc':'Засах, богиносгох, дэлгэрүүлэх, хураангуйлах, орчуулах.','tools.messageDesc':'Өнгө аястай editable draft бэлтгэнэ; автоматаар илгээхгүй.','tools.documentDesc':'Бүтэцтэй editable баримтын draft бэлтгэнэ.','tools.reminderDesc':'Browser хаалттай байсан ч хадгалагдах, UTC-д суурилсан ENKH сануулагч.',
  'chat.title':'ENKH Chat','chat.subtitle':'ENKH-тэй үргэлжилсэн яриа өрнүүлээрэй.','chat.placeholder':'Мессежээ бичнэ үү…','chat.send':'Илгээх','chat.sending':'Илгээж байна…','chat.error':'Сүлжээ эсвэл үйлчилгээний түр алдаа гарлаа. Таны асуулт history-д хадгалагдсан.','chat.empty':'Шинэ яриагаа эхлүүлээрэй.','chat.new':'Шинэ chat',
  'search.title':'Эх сурвалжтай вэб хайлт','search.subtitle':'Бодит вэбээс хайж, хариу болон эх сурвалжийг session-д хадгална.','search.saved':'Хадгалсан хайлтын үр дүн. Дахин нээхэд API дахин дуудагдахгүй.','search.placeholder':'Юу хайх вэ?','search.button':'Хайх','search.loading':'Вэбээс хайж байна…','search.failed':'Хайлт амжилтгүй','search.answer':'ENKH ХАРИУЛТ','search.sources':'Эх сурвалж','search.none':'Энэ хариунд тусдаа эх сурвалж ирсэнгүй.','search.historyError':'History хадгалах боломжгүй байна.','search.networkError':'Вэб хайлт хийхэд алдаа гарлаа. Query history-д хадгалагдсан тул дахин оролдож болно.',
  'workspace.title':'Workspace','workspace.subtitle':'Таны хадгалсан яриа, хайлт, тооцоолол болон бэлтгэсэн нооргууд.','workspace.newChat':'+ Шинэ chat','workspace.cloud':'CLOUD WORKSPACE','workspace.local':'LOCAL WORKSPACE','workspace.import':'Local workspace import','workspace.sync':'Cloud руу sync','workspace.load':'Cloud copy ачаалах','workspace.backup':'LOCAL BACKUP','workspace.empty':'Одоогоор хадгалсан ажил алга.','workspace.clear':'Бүх history арилгах','workspace.delete':'Устгах',
  'sync.local':'Local-д хадгалагдсан','sync.syncing':'Sync хийж байна…','sync.saved':'Cloud-д хадгалагдсан ✓','sync.pending':'Sync хүлээгдэж байна','sync.conflict':'Өөр төхөөрөмж дээр өөрчлөлт байна','sync.disabled':'Local-д хадгалагдсан',
  'account.title':'Account','account.subtitle':'ENKH account болон workspace-ийн төлөв.','account.checking':'Нэвтрэлтийн төлөв шалгаж байна…','account.unavailable':'Account service түр холбогдсонгүй','account.signInTitle':'ENKH account-д нэвтрэх','account.signInHelp':'Нэвтэрснээр Workspace-аа төхөөрөмжүүдийн хооронд аюулгүй хадгална. Одоогийн local ажлууд устахгүй.','account.signIn':'Нэвтрэх','account.yours':'ТАНЫ ACCOUNT','account.user':'ENKH хэрэглэгч','account.cloudActive':'Cloud Workspace идэвхтэй. Local ажлууд эхлээд энэ төхөөрөмж дээр аюулгүй хадгалагдана.','account.signOut':'Гарах',
  'status.title':'System status','status.subtitle':'Зардалгүй health check. AI хүсэлт автоматаар илгээхгүй.','status.online':'ONLINE','status.offline':'UNAVAILABLE','status.apiDesc':'Chat, Search, Tools-ийн үндсэн backend холбоо.','status.check':'Дахин шалгах','status.ai':'AI ба Search','status.aiDesc':'Бодит хүсэлт хийх үед баталгаажна. Status дэлгэц paid API call хийхгүй.','status.workspace':'Workspace','status.workspaceDesc':'Local-first: энэ browser-ийн хадгалалт ашиглана.',
  'draft.textTitle':'Текст боловсруулах','draft.textSubtitle':'Текстээ бодитоор засаж, богиносгож, дэлгэрүүлж, хураангуйлж эсвэл орчуулна.','draft.messageTitle':'Мессеж бэлтгэх','draft.messageSubtitle':'Зорилго, нөхцөл болон өнгө аясаар editable мессежийн ноорог бэлтгэнэ.','draft.documentTitle':'Баримт бичиг бэлтгэх','draft.documentSubtitle':'Төрөл, зорилго, нөхцөлд тохирсон бүтэцтэй editable ноорог бэлтгэнэ.','draft.operation':'Үйлдэл','draft.tone':'Өнгө аяс','draft.type':'Баримтын төрөл','draft.textInput':'Боловсруулах текст','draft.targetLanguage':'Орчуулах хэл','draft.instructions':'Нэмэлт чиглэл (заавал биш)','draft.recipient':'Хүлээн авагч (заавал биш)','draft.intent':'Мессежийн зорилго','draft.context':'Нөхцөл, дэлгэрэнгүй','draft.title':'Гарчиг (заавал биш)','draft.purpose':'Зорилго','draft.documentContext':'Агуулга, нөхцөл','draft.generating':'Үүсгэж байна…','draft.ready':'БЭЛЭН НООРОГ','draft.notSent':'Автоматаар илгээгдээгүй.','draft.docxNote':'Засварласан агуулгаас бодит Word файл үүснэ.','draft.docx':'DOCX татах','draft.editLabel':'Засварлах ноорог','draft.placeholder':'Мэдээллээ оруулна уу…',
  'calc.title':'Тооцоолол','calc.input':'Тооцооллын мэдээлэл','calc.example':'Жишээ','calc.run':'Гүйцэтгэх','calc.running':'ENKH ажиллаж байна...','calc.result':'Тооцооллын үр дүн','calc.base':'Үндсэн хэмжээ','calc.extra':'Илүүдэл','calc.extraValue':'Илүүдлийн хэмжээ','calc.total':'Нийт хэрэгцээ',
  'reminder.title':'Сануулагч','reminder.subtitle':'Огноо, цагийг нягтлаад хадгална. v1 хүргэлт ENKH дотор харагдана.','reminder.natural':'Байгалийн хэлээр бичих','reminder.parse':'Утгыг задлах','reminder.titleField':'Гарчиг / сануулах зүйл','reminder.note':'Нэмэлт тэмдэглэл','reminder.date':'Огноо (YYYY-MM-DD)','reminder.time':'Цаг (HH:mm)','reminder.timezone':'Timezone','reminder.delivery':'Хүргэлт: ENKH дотор · UTC-аар найдвартай товлоно','reminder.schedule':'Сануулагч товлох','reminder.saving':'Хадгалж байна…','reminder.reschedule':'Шинэ хуваарийг хадгалах','reminder.list':'Сануулагчид','reminder.empty':'Одоогоор сануулагч алга.',
} as const;

export type TranslationKey = keyof typeof mn;
type Dictionary = Record<TranslationKey, string>;
const en: Dictionary = Object.fromEntries(Object.keys(mn).map(k=>[k,mn[k as TranslationKey]])) as Dictionary;
Object.assign(en, {
  'language.label':'Language','nav.home':'Home','nav.search':'Search','nav.workspace':'Workspace','nav.tools':'Tools','nav.account':'Account','nav.status':'System','nav.primary':'Primary navigation','nav.utility':'Account and system navigation','brand.home':'ENKH home',
  'common.open':'Open →','common.retry':'Try again','common.loading':'Loading…','common.generate':'Generate','common.regenerate':'Generate again','common.copy':'Copy','common.save':'Save','common.cancel':'Cancel','common.edit':'Edit','common.details':'Details','common.hideDetails':'Hide details','common.back':'Back','common.working':'AVAILABLE',
  'home.greeting':'Hello!','home.subtitle':'What would you like to accomplish today?','home.prompt':'Ask ENKH anything…','home.ask':'Ask','home.aboutTitle':'What is ENKH?','home.about':'ENKH, or Enkh AI, is an AI product that helps with everyday questions, sourced web search, percentage and unit calculations, text processing, message drafting, and structured document creation.','home.what':'What would you like to do?','home.workspace':'Your ENKH workspace','home.recent':'Recent work','home.all':'View all →','home.empty':'Your workspace is empty','home.emptyHelp':'Your real work will appear here as you use ENKH.','home.workspaceOpen':'Open Workspace →',
  'feature.chatDesc':'Clear, continuous conversations','feature.search':'Search','feature.searchDesc':'Real search with sources','feature.workspaceDesc':'Your saved work','feature.toolsDesc':'Practical tools that work',
  'tool.calculation':'Calculation','tool.text':'Text Processing','tool.message':'Message Drafting','tool.document':'Document Drafting','tool.reminder':'Reminder',
  'tools.title':'ENKH Tools','tools.subtitle':'Working tools that help prepare your work faster.','tools.active':'Available','tools.run':'Run','tools.process':'Process','tools.draft':'Create draft','tools.schedule':'Schedule','tools.calcDesc':'Numbers, percentages, and unit calculations.','tools.textDesc':'Polish, shorten, expand, summarize, and translate.','tools.messageDesc':'Create an editable draft in your chosen tone; never sent automatically.','tools.documentDesc':'Create a structured, editable document draft.','tools.reminderDesc':'Durable UTC-based ENKH reminders that persist when the browser is closed.',
  'chat.title':'ENKH Chat','chat.subtitle':'Have a continuous conversation with ENKH.','chat.placeholder':'Write a message…','chat.send':'Send','chat.sending':'Sending…','chat.error':'A temporary network or service error occurred. Your question remains in history.','chat.empty':'Start a new conversation.','chat.new':'New chat',
  'search.title':'Web search with sources','search.subtitle':'Search the real web and save the answer and sources in a session.','search.saved':'Saved search result. Reopening does not call the API again.','search.placeholder':'What do you want to find?','search.button':'Search','search.loading':'Searching the web…','search.failed':'Search failed','search.answer':'ENKH ANSWER','search.sources':'Sources','search.none':'No separate sources were returned for this answer.','search.historyError':'History could not be saved.','search.networkError':'Web search failed. Your query remains in history so you can retry.',
  'workspace.subtitle':'Your saved conversations, searches, calculations, and drafts.','workspace.newChat':'+ New chat','workspace.import':'Import local workspace','workspace.sync':'Sync to cloud','workspace.load':'Load cloud copy','workspace.backup':'LOCAL BACKUP','workspace.empty':'No saved work yet.','workspace.clear':'Clear all history','workspace.delete':'Delete',
  'sync.local':'Saved locally','sync.syncing':'Syncing…','sync.saved':'Saved to cloud ✓','sync.pending':'Sync pending','sync.conflict':'Changes exist on another device','sync.disabled':'Saved locally',
  'account.subtitle':'Your ENKH account and workspace status.','account.checking':'Checking sign-in status…','account.unavailable':'Account service is temporarily unavailable','account.signInTitle':'Sign in to your ENKH account','account.signInHelp':'Sign in to keep your Workspace safely available across devices. Your current local work will not be deleted.','account.signIn':'Sign in','account.yours':'YOUR ACCOUNT','account.user':'ENKH user','account.cloudActive':'Cloud Workspace is active. Work is stored safely on this device first.','account.signOut':'Sign out',
  'status.subtitle':'A free health check. No AI request is sent automatically.','status.apiDesc':'Core backend connection for Chat, Search, and Tools.','status.check':'Check again','status.ai':'AI and Search','status.aiDesc':'Verified when you make a real request. This screen makes no paid API call.','status.workspaceDesc':'Local-first: uses storage in this browser.',
  'draft.textTitle':'Text Processing','draft.textSubtitle':'Polish, shorten, expand, summarize, or translate your text.','draft.messageTitle':'Message Drafting','draft.messageSubtitle':'Create an editable message draft from intent, context, and tone.','draft.documentTitle':'Document Drafting','draft.documentSubtitle':'Create a structured, editable draft for your document type and purpose.','draft.operation':'Operation','draft.tone':'Tone','draft.type':'Document type','draft.textInput':'Text to process','draft.targetLanguage':'Target language','draft.instructions':'Additional instructions (optional)','draft.recipient':'Recipient (optional)','draft.intent':'Message intent','draft.context':'Context and details','draft.title':'Title (optional)','draft.purpose':'Purpose','draft.documentContext':'Content and context','draft.generating':'Generating…','draft.ready':'READY DRAFT','draft.notSent':'Not sent automatically.','draft.docxNote':'A real Word file is created from the edited content.','draft.docx':'Download DOCX','draft.editLabel':'Editable draft','draft.placeholder':'Enter information…',
  'calc.title':'Calculation','calc.input':'Calculation details','calc.example':'Example','calc.run':'Run','calc.running':'ENKH is working...','calc.result':'Calculation result','calc.base':'Base amount','calc.extra':'Extra','calc.extraValue':'Extra amount','calc.total':'Total required',
  'reminder.title':'Reminder','reminder.subtitle':'Review the date and time before saving. v1 delivery appears inside ENKH.','reminder.natural':'Describe naturally','reminder.parse':'Parse details','reminder.titleField':'Title / reminder','reminder.note':'Additional note','reminder.date':'Date (YYYY-MM-DD)','reminder.time':'Time (HH:mm)','reminder.timezone':'Timezone','reminder.delivery':'Delivery: in ENKH · reliably scheduled in UTC','reminder.schedule':'Schedule reminder','reminder.saving':'Saving…','reminder.reschedule':'Save new schedule','reminder.list':'Reminders','reminder.empty':'No reminders yet.'
});
const zh: Dictionary = Object.fromEntries(Object.keys(mn).map(k=>[k,mn[k as TranslationKey]])) as Dictionary;
Object.assign(zh, {
  'language.label':'语言','nav.home':'首页','nav.chat':'聊天','nav.search':'搜索','nav.workspace':'工作区','nav.tools':'工具','nav.account':'账户','nav.status':'系统','nav.primary':'主导航','nav.utility':'账户和系统导航','brand.home':'ENKH 首页',
  'common.open':'打开 →','common.retry':'重试','common.loading':'加载中…','common.generate':'生成','common.regenerate':'重新生成','common.copy':'复制','common.save':'保存','common.cancel':'取消','common.edit':'编辑','common.details':'详情','common.hideDetails':'收起详情','common.back':'返回','common.working':'可用',
  'home.greeting':'您好！','home.subtitle':'今天想完成什么？','home.prompt':'向 ENKH 提问…','home.ask':'提问','home.aboutTitle':'什么是 ENKH？','home.about':'ENKH（Enkh AI）是一款 AI 产品，可协助日常问答、带来源的网页搜索、百分比和单位计算、文本处理、消息起草及结构化文档制作。','home.what':'您想做什么？','home.workspace':'您的 ENKH 工作区','home.recent':'最近工作','home.all':'查看全部 →','home.empty':'工作区为空','home.emptyHelp':'使用 ENKH 后，您的实际工作会显示在这里。','home.workspaceOpen':'打开工作区 →',
  'feature.chat':'聊天','feature.chatDesc':'清晰、连续的对话','feature.search':'搜索','feature.searchDesc':'带来源的真实搜索','feature.workspace':'工作区','feature.workspaceDesc':'您保存的工作','feature.tools':'工具','feature.toolsDesc':'真正可用的实用工具',
  'tool.calculation':'计算','tool.text':'文本处理','tool.message':'消息起草','tool.document':'文档起草','tool.reminder':'提醒',
  'tools.title':'ENKH 工具','tools.subtitle':'帮助您更快完成工作的实用工具。','tools.active':'可用','tools.run':'运行','tools.process':'处理','tools.draft':'创建草稿','tools.schedule':'设置','tools.calcDesc':'数值、百分比和单位计算。','tools.textDesc':'润色、缩短、扩写、总结和翻译。','tools.messageDesc':'按所选语气创建可编辑草稿；不会自动发送。','tools.documentDesc':'创建结构化、可编辑的文档草稿。','tools.reminderDesc':'关闭浏览器后仍可保存的 UTC ENKH 提醒。',
  'chat.title':'ENKH 聊天','chat.subtitle':'与 ENKH 进行连续对话。','chat.placeholder':'输入消息…','chat.send':'发送','chat.sending':'发送中…','chat.error':'网络或服务暂时出错。您的问题仍保存在历史记录中。','chat.empty':'开始新对话。','chat.new':'新建聊天',
  'search.title':'带来源的网页搜索','search.subtitle':'搜索真实网页，并将回答和来源保存到会话。','search.saved':'已保存的搜索结果。重新打开不会再次调用 API。','search.placeholder':'您想搜索什么？','search.button':'搜索','search.loading':'正在搜索网页…','search.failed':'搜索失败','search.answer':'ENKH 回答','search.sources':'来源','search.none':'此回答未返回单独来源。','search.historyError':'无法保存历史记录。','search.networkError':'网页搜索失败。查询已保留，可重试。',
  'workspace.title':'工作区','workspace.subtitle':'您保存的对话、搜索、计算和草稿。','workspace.newChat':'+ 新建聊天','workspace.import':'导入本地工作区','workspace.sync':'同步到云端','workspace.load':'加载云端副本','workspace.backup':'本地备份','workspace.empty':'暂无保存的工作。','workspace.clear':'清除全部历史','workspace.delete':'删除',
  'sync.local':'已保存到本地','sync.syncing':'正在同步…','sync.saved':'已保存到云端 ✓','sync.pending':'等待同步','sync.conflict':'其他设备上有更改','sync.disabled':'已保存到本地',
  'account.title':'账户','account.subtitle':'您的 ENKH 账户和工作区状态。','account.checking':'正在检查登录状态…','account.unavailable':'账户服务暂时不可用','account.signInTitle':'登录 ENKH 账户','account.signInHelp':'登录后可在设备间安全使用工作区。当前本地工作不会被删除。','account.signIn':'登录','account.yours':'您的账户','account.user':'ENKH 用户','account.cloudActive':'云工作区已启用。工作会先安全保存到本设备。','account.signOut':'退出登录',
  'status.title':'系统状态','status.subtitle':'免费健康检查，不会自动发送 AI 请求。','status.online':'在线','status.offline':'不可用','status.apiDesc':'聊天、搜索和工具的核心后端连接。','status.check':'重新检查','status.ai':'AI 和搜索','status.aiDesc':'发起实际请求时进行验证。本页面不会产生付费 API 调用。','status.workspace':'工作区','status.workspaceDesc':'本地优先：使用此浏览器的存储。',
  'draft.textTitle':'文本处理','draft.textSubtitle':'润色、缩短、扩写、总结或翻译文本。','draft.messageTitle':'消息起草','draft.messageSubtitle':'根据意图、上下文和语气创建可编辑消息草稿。','draft.documentTitle':'文档起草','draft.documentSubtitle':'根据文档类型和目的创建结构化、可编辑的草稿。','draft.operation':'操作','draft.tone':'语气','draft.type':'文档类型','draft.textInput':'待处理文本','draft.targetLanguage':'目标语言','draft.instructions':'附加说明（可选）','draft.recipient':'收件人（可选）','draft.intent':'消息意图','draft.context':'上下文和详情','draft.title':'标题（可选）','draft.purpose':'目的','draft.documentContext':'内容和上下文','draft.generating':'生成中…','draft.ready':'草稿已就绪','draft.notSent':'未自动发送。','draft.docxNote':'将从编辑后的内容创建真实 Word 文件。','draft.docx':'下载 DOCX','draft.editLabel':'可编辑草稿','draft.placeholder':'请输入信息…',
  'calc.title':'计算','calc.input':'计算信息','calc.example':'示例','calc.run':'运行','calc.running':'ENKH 正在处理...','calc.result':'计算结果','calc.base':'基础数值','calc.extra':'附加比例','calc.extraValue':'附加数值','calc.total':'总需求',
  'reminder.title':'提醒','reminder.subtitle':'保存前请确认日期和时间。v1 提醒会显示在 ENKH 内。','reminder.natural':'自然语言描述','reminder.parse':'解析信息','reminder.titleField':'标题 / 提醒事项','reminder.note':'附加备注','reminder.date':'日期 (YYYY-MM-DD)','reminder.time':'时间 (HH:mm)','reminder.timezone':'时区','reminder.delivery':'投递：ENKH 内 · 使用 UTC 可靠调度','reminder.schedule':'设置提醒','reminder.saving':'保存中…','reminder.reschedule':'保存新时间','reminder.list':'提醒列表','reminder.empty':'暂无提醒。'
});

export const dictionaries: Record<UiLanguage, Dictionary> = { mn, en, zh };
export const languageOptions = [{id:'mn',label:'Монгол',short:'MN'},{id:'en',label:'English',short:'EN'},{id:'zh',label:'中文（简体）',short:'中'}] as const;
const isLanguage=(value:unknown):value is UiLanguage=>value==='mn'||value==='en'||value==='zh';
type I18nValue={language:UiLanguage;setLanguage:(language:UiLanguage)=>void;t:(key:TranslationKey)=>string};
const I18nContext=createContext<I18nValue|undefined>(undefined);

export function LanguageProvider({children}:{children:ReactNode}) {
  const [language,setLanguageState]=useState<UiLanguage>('mn');
  useEffect(()=>{try{const saved=globalThis.localStorage?.getItem(LANGUAGE_STORAGE_KEY);if(isLanguage(saved))setLanguageState(saved);}catch{}},[]);
  const setLanguage=useCallback((next:UiLanguage)=>{setLanguageState(next);try{globalThis.localStorage?.setItem(LANGUAGE_STORAGE_KEY,next);}catch{}},[]);
  const value=useMemo<I18nValue>(()=>({language,setLanguage,t:(key)=>dictionaries[language][key]}),[language,setLanguage]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error('useI18n must be used inside LanguageProvider');return value;}
export function syncLabelKey(phase:string):TranslationKey{return phase==='syncing'?'sync.syncing':phase==='saved'?'sync.saved':phase==='pending'?'sync.pending':phase==='conflict'?'sync.conflict':phase==='disabled'?'sync.disabled':'sync.local';}
